name: outputs workflow
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.mesg }}
      output2: ${{ steps.step2.outputs.mesg }}
    steps:
      - id: step1
        run: echo  "mesg=hello"  >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo  "mesg=world"  >> "$GITHUB_OUTPUT"
