name: First workflow2
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: "hello"
      output2: "world"
    steps:
      - id: step1
        run: echo  "${{jobs.job1.outputs.output1}}"
      - id: step2
        run: echo  world
